config/routes.rb
RiddlerAdmin::Engine.routes.draw do
  root to: "dashboard#index"

  resources :actions do
    put "sort", on: :collection
  end

  resources :elements do
    put "sort", on: :collection
  end

  resources :preview_contexts

  resources :publish_requests do
    post "approve", on: :member
    post "publish", on: :member
  end

  resources :steps do
    put "sort", on: :collection

    get "internal_preview", on: :member
    post "preview", on: :member
    get "preview", on: :member
    get "toggle", on: :member
  end

  resources :slugs
end

app/models/riddler_admin/action.rb
module RiddlerAdmin
  class Action < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "act".freeze
    ID_LENGTH = 6

    belongs_to :actionable, polymorphic: true, validate: true

    acts_as_list scope: [:actionable_type, :actionable_id, :transition_type]

    validates :transition_type, presence: true, inclusion: { in: %w[ enter exit ] }

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates :name, presence: true,
      format: {
        with: /\A[a-z][a-zA-Z0-9_]*\z/,
        message: "must be a valid variable name (no spaces, start with character)"
      }

    validates_uniqueness_of :name, scope: [:actionable_type, :actionable_id]

    validates :include_predicate, parseable_predicate: true

    before_validation :set_defaults

    def self.available_classes
      [
        Actions::Assignment,
        Actions::HTTPRequest
      ]
    end

    def self.default_class
      Actions::Assignment
    end

    def self.short_name
      name.demodulize
    end

    def short_name
      self.class.short_name
    end

    def object
      type.demodulize
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      hash
    end

    def serializable_hash_options
      {
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :actionable_type, :actionable_id, :position, :transition_type, :options]
    end

    private

    def set_defaults
      self.name = short_name.underscore if name.blank?
    end
  end
end

app/models/riddler_admin/actions/assignment.rb
module RiddlerAdmin
  module Actions
    class Assignment < ::RiddlerAdmin::Action
      def self.model_name
        ::RiddlerAdmin::Action.model_name
      end

      def definition_hash opts=nil
        hash = super
        hash["variable"] = options["variable"]
        hash["value_template"] = options["value_template"]
        hash
      end
    end
  end
end

app/models/riddler_admin/actions/http_request.rb
module RiddlerAdmin
  module Actions
    class HTTPRequest < ::RiddlerAdmin::Action
      def self.model_name
        ::RiddlerAdmin::Action.model_name
      end

      def definition_hash opts=nil
        hash = super
        hash["request_method"] = options["request_method"]
        hash["url_template"] = options["url_template"]
        hash["body_template"] = options["body_template"]
        hash
      end
    end
  end
end

app/models/riddler_admin/application_record.rb
require "ulid"

module RiddlerAdmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    after_initialize :generate_id

    private

    def id_length
      return 16 unless self.class.const_defined? :ID_LENGTH
      self.class.const_get :ID_LENGTH
    end

    def generate_id
      return if id.present?
      model_key = self.class.const_get :MODEL_KEY
      ulid = ULID.generate
      id_string = ulid[0..(9+id_length)]
      self.id = [model_key, id_string].join "_"
    end
  end
end

app/models/riddler_admin/content_version.rb
require "riddler/protobuf/content_version_pb"
require "riddler/protobuf/content_management_services_pb"

module RiddlerAdmin
  class ContentVersion < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cver".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def description
      publish_request.title
    end

    def title
      "#{content.title} v#{version} - #{description}"
    end

    def to_proto
      ::Riddler::Protobuf::ContentVersion.new \
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        title: content.title,
        description: description,
        version: version,
        definition_schema_version: DEFINITION_SCHEMA_VERSION,
        definition_string: definition.to_json
    end

    def publish_to_remote
      content_management_grpc.create_content_version create_request_proto
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def create_request_proto
      ::Riddler::Protobuf::CreateContentVersionRequest.new \
        content_version: self.to_proto
    end

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.definition_schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/element.rb
module RiddlerAdmin
  class Element < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "el".freeze
    ID_LENGTH = 6 # 56_800_235_584 per second

    after_initialize :set_defaults

    belongs_to :container, polymorphic: true, validate: true

    acts_as_list scope: [:container_type, :container_id]

    validates_presence_of :name

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates_format_of :name, with: /\A[a-z][a-zA-Z0-9_]*\z/, message: "cannot start with a capital letter or a number."
    validates_uniqueness_of :name, scope: [:container_type, :container_id], unless: :is_variant?

    validates :include_predicate, parseable_predicate: true

    def self.available_classes
      [
        Elements::Heading,
        Elements::Image,
        Elements::Link,
        Elements::Text,
        Elements::Variant
      ]
    end

    def self.default_class
      Elements::Text
    end

    def self.short_name
      name.demodulize
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    def short_name
      self.class.short_name
    end

    # Used in serialization
    def object
      type.demodulize
    end

    def content_type
      "Element"
    end

    def content_id
      id
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      hash
    end

    def serializable_hash_options
      {
        methods: [:content_type],
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :container_type, :container_id, :position, :url, :text]
    end

    def step
      if container.kind_of? ::RiddlerAdmin::Step
        container
      else
        container.step
      end
    end

    private

    def is_variant?
      container.kind_of? ::RiddlerAdmin::Elements::Variant
    end

    def set_defaults
      self.name = short_name.underscore if name.blank?
    end
  end
end

app/models/riddler_admin/elements/heading.rb
module RiddlerAdmin
  module Elements
    class Heading < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/image.rb
module RiddlerAdmin
  module Elements
    class Image < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["src"] = url
        hash["alt"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/link.rb
module RiddlerAdmin
  module Elements
    class Link < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["href"] = url
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/text.rb
module RiddlerAdmin
  module Elements
    class Text < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/variant.rb
module RiddlerAdmin
  module Elements
    class Variant < Element
      has_many :elements, -> { order position: :asc },
        dependent: :destroy,
        as: :container

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["elements"] = elements.map { |e| e.definition_hash }
        hash
      end
    end
  end
end

app/models/riddler_admin/preview_context.rb
require "riddler/protobuf/content_management_services_pb"

module RiddlerAdmin
  class PreviewContext < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "pctx".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    validates :title, presence: true, uniqueness: true

    def self.convert_headers input_headers
      original_headers = input_headers.to_h.
        select{|k,v| k.starts_with? "HTTP_"}.
        map{|k,v| [k.downcase.gsub(/^http_/, ""), v] }

      Hash[original_headers]
    end

    def data
      yaml_string = yaml

      if ::RiddlerAdmin.configuration.encrypt_preview_contexts? &&
        encrypted_yaml.present?

        yaml_string = decrypt encrypted_yaml
      end

      return {} if yaml_string.to_s.strip == ""
      YAML.safe_load yaml_string
    end

    def refresh_data input_headers: {}
      use_case_headers = merge_headers input_headers
      hash = {}

      if ::RiddlerAdmin.configuration.remote_riddler?
        input_json = {params: params_hash, headers: use_case_headers}.to_json

        request_proto = ::Riddler::Protobuf::GenerateContextRequest.new \
          input_json: input_json

        context_proto = content_management_grpc.generate_context request_proto
        hash = JSON.parse context_proto.context_json

      else
        use_case = ::Riddler::UseCases::PreviewContext.new \
          params: params_hash,
          headers: use_case_headers

        hash = use_case.process
      end

      update_data hash
    end

    def params_hash
      params_array = (params || "").split("\n").map do |line|
        line.split(":").map &:strip
      end
      Hash[params_array]
    end

    def headers_hash
      headers_array = (headers || "").split("\n").map do |line|
        key, val = *line.split(":").map(&:strip)
        [key.downcase.gsub(/[^0-9a-z]/i, "_"), val]
      end
      Hash[headers_array]
    end

    def merge_headers input_headers
      request_headers = self.class.convert_headers input_headers
      request_headers.merge headers_hash
    end

    def update_data hash
      yaml = hash.to_yaml

      if ::RiddlerAdmin.configuration.encrypt_preview_contexts?
        encrypted_yaml = encrypt yaml
        update_attribute :encrypted_yaml, encrypted_yaml
      else
        update_attribute :yaml, yaml
      end
    end

    private

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure
    end

    def encrypt plaintext
      ::RiddlerAdmin.encrypt plaintext,
        key: ::RiddlerAdmin.configuration.preview_context_transit_key
    end

    def decrypt ciphertext
      ::RiddlerAdmin.decrypt ciphertext,
        key: ::RiddlerAdmin.configuration.preview_context_transit_key
    end
  end
end

app/models/riddler_admin/steps/content.rb
module RiddlerAdmin
  module Steps
    class Content < Step
      has_many :elements, -> { order position: :asc },
        dependent: :destroy,
        as: :container

      def self.model_name
        Step.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["elements"] = elements.map { |e| e.definition_hash }
        hash
      end
    end
  end
end

app/controllers/riddler_admin/actions_controller.rb
require_dependency "riddler_admin/application_controller"

module RiddlerAdmin
  class ActionsController < ApplicationController
    before_action :set_action, only: [:show, :edit, :update, :destroy]
    before_action :set_action_class

    # GET /actions/new
    def new
      hash = {}

      if step = Step.find_by_id(params["step_id"])
        hash[:actionable] = step
      end

      @action = @action_class.new hash
    end

    # POST /actions
    def create
      @action = @action_class.new action_create_params

      if @action.save
        render :show
      else
        render :new
      end
    end

    # PATCH/PUT /actions/1
    def update
      if @action.update action_params
        redirect_to @action, notice: 'Action was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /actions/1
    def destroy
      @action.destroy
      render :destroy
    end

    # PUT /actions/sort
    def sort
      action_order = params.fetch "action_order"

      action_order.each_with_index do |action_id, index|
        action = Action.find_by_id action_id
        action.update_attribute :position, index+1
      end

      head :no_content
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_action
        @action = Action.find params[:id]
      end

      def set_action_class
        class_name = params.fetch(:ra_action, {}).delete("type") ||
          params.delete(:type)
        class_name = RiddlerAdmin::Action.default_class.name if class_name.blank?

        @action_class = class_name.constantize
      end

      # Only allow a trusted parameter "white list" through.
      def action_create_params
        params.require(:ra_action).permit(:id, :name, :type, :actionable_type, :actionable_id,
                                          :include_predicate, :transition_type,
                                          options: [:variable, :value_template,
                                                    :request_method, :url_template, :body_template])
      end

      # Only allow a trusted parameter "white list" through.
      def action_params
        params.require(:ra_action).permit(:name, :include_predicate, :transition_type,
                                          options: [:variable, :value_template,
                                                    :request_method, :url_template, :body_template])
      end
  end
end

app/controllers/riddler_admin/application_controller.rb
module RiddlerAdmin
  class ApplicationController < ::RiddlerAdmin.config.base_controller
    before_action :authorize_riddler_admin
    helper_method :riddler_current_user, :riddler_user_can_approve?, :riddler_user_can_deploy?

    def riddler_current_user
      self.send ::RiddlerAdmin.config.current_user_method
    end

    def riddler_user_can_approve?
      return true if ::RiddlerAdmin.config.user_can_approve_block.nil?
      ::RiddlerAdmin.config.user_can_approve_block.call riddler_current_user
    end

    def riddler_user_can_deploy?
      return true if ::RiddlerAdmin.config.user_can_deploy_block.nil?
      ::RiddlerAdmin.config.user_can_deploy_block.call riddler_current_user
    end

    private

    def authorize_riddler_admin
      return true if ::RiddlerAdmin.config.controller_authorization_block.nil?
      ::RiddlerAdmin.config.controller_authorization_block.call self
    end
  end
end

app/controllers/riddler_admin/dashboard_controller.rb
require_dependency "riddler_admin/application_controller"

module RiddlerAdmin
  class DashboardController < ApplicationController
    def index
    end
  end
end

app/views/riddler_admin/steps/_actions.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h4>Add an action</h4>

      <ul class="nav flex-column">
      <% RiddlerAdmin::Action.available_classes.each do |klass| %>
        <%= link_to "#{klass.short_name}", new_action_path(type: klass.name, step_id: @step.id), remote: true, class: 'nav-link' %>
      <% end %>
      </ul>
    </div>
    <div class="col-md-9">
      <div id="new-action">
      </div>

      <%= render partial: "riddler_admin/action_container", locals: { actionable: @step } %>

    </div>
  </div>
</div>

app/views/riddler_admin/steps/_definition.html.erb
<div class="row">
  <div class="col-sm">
    <h4>Step Definition</h4>
  </div>
</div>

<div class="row">
  <div class="col-sm">
    <pre><%= definition.definition_hash.to_yaml %></pre>
  </div>
</div>

app/views/riddler_admin/steps/_form.html.erb
<%= form_with model: step, local: true do |form| %>
  <div class="row">
    <% if step.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

        <ul>
        <% step.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <div class="form-row">
      <div class="col">
        <%= form.label :title %>
        <%= form.text_field :title, class:"form-control" %>
      </div>
      <div class="col">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
        <small class="form-text text-muted">This will be created based on the title if not provided</small>
      </div>
    </div>
    <% unless @step.persisted? %>
    <div class="form-row">
      <div class="col">
        <%= form.label :type %>
        <%= form.select :type, options_for_select(::RiddlerAdmin::Step.available_classes.map{|klass| [klass.short_name, klass.name]}, step.type), {}, class:"form-control" %>
      </div>
    </div>
    <% end %>
    <div class="form-row">
      <div class="col">
        <%= form.label :include_predicate %>
        <%= form.text_field :include_predicate, class: "form-control", placeholder: "e.g. params.user_id is present" %>
        <small class="form-text text-muted">Use data from the context that evaluates to <code>true</code> or <code>false</code></small>
      </div>
    </div>
    <div class="form-row">
      <div class="actions">
        <%= form.submit "Save step", class: "btn btn-primary" %>
        <%= link_to "Cancel", steps_path, class: "btn btn-light" %>
      </div>
    </div>
  </div>
<% end %>

app/views/riddler_admin/steps/_new_sub_step.html.erb
<%= form_with model: step do |form| %>
  <% if step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card" style="margin-bottom: 32px;">
    <div class="card-body">

      <div class="card-title">
        <h5>New <%= step.short_name %> Step</h5>
      </div>

      <%= form.hidden_field :type %>
      <%= form.hidden_field :stepable_type %>
      <%= form.hidden_field :stepable_id %>

      <div class="form-group">
        <div class="form-row">
          <div class="col">
            <%= form.label :title %>
            <%= form.text_field :title, class:"form-control" %>
          </div>
          <div class="col">
            <%= form.label :name %>
            <%= form.text_field :name, class:"form-control" %>
            <small class="form-text text-muted">This will be created based on the title if not provided</small>
          </div>
        </div>

        <div class="form-row">
          <div class="col">
            <%= form.label :include_predicate %>
            <%= form.text_field :include_predicate, class: "form-control", placeholder: "e.g. params.user_id is present" %>
            <small class="form-text text-muted">Use data from the context that evaluates to <code>true</code> or <code>false</code></small>
          </div>
        </div>


        <div class="form-row">
          <div class="actions">
            <%= form.submit "Add step", class: "btn btn-primary" %>
          </div>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/riddler_admin/steps/_visual_preview.html.erb
<ul class="list-group">
  <% if data["elements"].blank? %>
    <li class="list-group-item">
      <%= data["message"] %>
    </li>
  <% else %>
    <% data["elements"].each do |element| %>
      <li class="list-group-item">
        <% case element["type"] %>
        <% when "Link" %>
          <a href="<%= element["href"] %>" target="_blank"><%= element["text"] %></a>
        <% when "Heading" %>
          <h5><%= element["text"] %></h5>
        <% when "Image" %>
          <img src="<%= element["src"] %>" alt="<%= element["alt"] %>" />
        <% when "Text" %>
          <%= element["text"] %>
        <% else %>
          Unknown Element type "<%= element["type"] %>"
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/riddler_admin/steps/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <h1>Editing Step</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <%= render 'form', step: @step %>

        <%= link_to 'Back', @step %>
      </div>
    </div>
  </div>
</div>

app/views/riddler_admin/steps/index.html.erb
<div class="row">
  <% if notice %>
  <div class="col-sm">
    <span id="notice"><%= notice %></span>
  </div>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-6">
    <h1>Steps</h1>
  </div>
  <div class="col-sm-6">
    <%= link_to 'New step', new_step_path, class: 'btn btn-primary float-right'%>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Id</th>
      <th>Type</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= link_to step.title, step %></td>
        <td><%= step.id %></td>
        <td><%= step.type.demodulize %></td>

        <td>
            <%= link_to 'Delete', step, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/riddler_admin/steps/internal_preview.js.erb
$("#<%= @preview_context.id %>-json pre")
  .html("<%= j JSON.pretty_generate @preview_hash %>");

$("#<%= @preview_context.id %>-visual")
  .html("<%= j render partial: "riddler_admin/steps/visual_preview", locals: { data: @preview_hash } %>")

app/views/riddler_admin/steps/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <h1>New Step</h1>
      </div>
    </div>
    <%= render "form", step: @step %>
  </div>
</div>

app/views/riddler_admin/steps/new.js.erb
$("#new-step")
  .html("<%= j render partial: "new_sub_step", locals: { step: @step } %>")
  .show()

app/views/riddler_admin/steps/preview.json.erb
<%= @use_case.process.to_json.html_safe %>

app/views/riddler_admin/steps/show.html.erb
<div class="row">
  <div class="col-sm">
    <% if notice %>
    <div class="alert alert-success">
      <span id="notice"><%= notice %></span>
    </div>
    <% end %>
  </div>
</div>

<div class="row" style="margin-bottom: 32px;">
  <div class="col-sm-6">
    <h1><%= @step.title %></h1>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Edit Step', edit_step_path(@step), class: 'btn btn-light float-right' %>
    <%= link_to "#{@step.preview_enabled ? 'Disable' : 'Enable'} Preview", toggle_step_path(@step), class: 'btn btn-light float-right mr-2' %>
    <% if ::RiddlerAdmin.configuration.remote_riddler? %>
      <%= link_to "Publish", new_publish_request_path(step_id: @step.id), class: "btn btn-light float-right"%>
    <% end %>
    <% if @step.preview_enabled %>
      <span class="badge badge-success float-right mr-2 mt-2">Preview Enabled</span>
    <% else %>
      <span class="badge badge-secondary float-right mr-2 mt-2">Preview Disabled</span>
    <% end %>
  </div>
</div>

<%= render partial: @step.to_partial_path("show") %>

app/views/riddler_admin/steps/show.js.erb
$("#new-step").fadeOut().html("").show();

$("#<%= @step.stepable.id %>-steps")
  .html("<%= j render partial: "riddler_admin/step", collection: @step.stepable.steps %>")