config/routes.rb
RiddlerAdmin::Engine.routes.draw do
  root to: "dashboard#index"

  resources :actions do
    put "sort", on: :collection
  end

  resources :elements do
    put "sort", on: :collection
  end

  resources :preview_contexts

  resources :publish_requests do
    post "approve", on: :member
    post "publish", on: :member
  end

  resources :steps do
    put "sort", on: :collection

    get "internal_preview", on: :member
    post "preview", on: :member
    get "preview", on: :member
    get "toggle", on: :member
  end

  resources :slugs
end

app/models/riddler_admin/step.rb
module RiddlerAdmin
  class Step < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "st".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    belongs_to :stepable, polymorphic: true, optional: true
    acts_as_list scope: [:stepable_type, :stepable_id]

    validates_presence_of :title

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates :name, presence: true,
      format: {
        with: /\A[a-z][a-zA-Z0-9_]*\z/,
        message: "must be a valid variable name (no spaces, start with character)"
      }

    validates :include_predicate, parseable_predicate: true

    has_many :enter_actions,
      -> { where("transition_type = ?", "enter").order(position: :asc) },
      class_name: "::RiddlerAdmin::Action",
      dependent: :destroy,
      as: :actionable

    has_many :exit_actions,
      -> { where("transition_type = ?", "exit").order(position: :asc) },
      class_name: "::RiddlerAdmin::Action",
      dependent: :destroy,
      as: :actionable

    has_many :publish_requests,
      dependent: :nullify,
      as: :content

    has_many :content_versions,
      dependent: :nullify,
      as: :content

    before_validation :set_defaults

    def self.available_classes
      [
        Steps::Content,
        Steps::Variant
      ]
    end

    def self.default_class
      Steps::Content
    end

    def self.short_name
      name.demodulize
    end

    def short_name
      self.class.short_name
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    # Used in serialization
    def object
      type.demodulize
    end

    def content_type
      "Step"
    end

    def content_id
      id
    end

    def published?
      content_versions.any?
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      if enter_actions.any?
        hash["enter_actions"] = enter_actions.map{ |a| a.definition_hash }
      end
      if exit_actions.any?
        hash["exit_actions"] = exit_actions.map{ |a| a.definition_hash }
      end
      hash
    end

    def serializable_hash_options
      {
        methods: [:content_type],
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :title, :preview_enabled, :stepable_type, :stepable_id, :position]
    end

    private

    def set_defaults
      return if name.present?
      self.name = self.title.parameterize.underscore
    end
  end
end

app/models/riddler_admin/steps/content.rb
module RiddlerAdmin
  module Steps
    class Content < Step
      has_many :elements, -> { order position: :asc },
        dependent: :destroy,
        as: :container

      def self.model_name
        Step.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["elements"] = elements.map { |e| e.definition_hash }
        hash
      end
    end
  end
end

app/models/riddler_admin/steps/variant.rb
module RiddlerAdmin
  module Steps
    class Variant < Step
      has_many :steps, -> { order position: :asc },
        dependent: :destroy,
        as: :stepable

      def self.model_name
        Step.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["steps"] = steps.map { |s| s.definition_hash }
        hash
      end
    end
  end
end

app/controllers/riddler_admin/steps_controller.rb
require "riddler/protobuf/content_management_services_pb"
require_dependency "riddler_admin/application_controller"

module RiddlerAdmin
  class StepsController < ApplicationController
    before_action :set_step, only: [:show, :edit, :update, :destroy, :internal_preview, :preview, :toggle]
    before_action :set_step_class

    # GET /steps
    def index
      @steps = Step.all
    end

    # GET /steps/1
    def show
      @step_definition = @step.definition_hash
      @preview_contexts = ::RiddlerAdmin::PreviewContext.all
    end

    # GET /steps/new
    def new
      hash = {}

      if step = Step.find_by_id(params["step_id"])
        hash[:stepable] = step
      end

      @step = @step_class.new hash
    end

    # GET /steps/1/edit
    def edit
    end

    # Should always comes from the admin tool
    def internal_preview
      @preview_context = ::RiddlerAdmin::PreviewContext.find_by_id params["pctx_id"]
      if @preview_context.nil?
        render(status: 400, json: {message: "Invalid pctx_id"}) and return
      end

      if ::RiddlerAdmin.configuration.remote_riddler?
        begin
          request_proto = ::Riddler::Protobuf::PreviewContentRequest.new \
            definition_json: @step.definition_hash.to_json,
            context_json: @preview_context.data.to_json

          content_proto = content_management_grpc.preview_content request_proto
          @preview_hash = JSON.parse content_proto.content_json
        rescue GRPC::Unavailable, GRPC::DeadlineExceeded
          @preview_hash = {"message" => "gRPC unavailable: #{$!}"}
        end
      else
        use_case = ::Riddler::UseCases::AdminPreviewStep.new @step.definition_hash,
          preview_context_data: @preview_context.data

        @preview_hash = use_case.process.deep_stringify_keys
      end
    end

    def sort
      step_order = params.fetch "step_order"

      step_order.each_with_index do |step_id, index|
        step = Step.find_by_id step_id
        step.update_attribute :position, index+1
      end

      head :no_content
    end

    # POST /steps/1/preview
    def preview
      if @step.preview_enabled
        request_headers = PreviewContext.convert_headers request.headers.to_h
        definition = @step.definition_hash

        use_case = ::Riddler::UseCases::PreviewStep.new definition,
          params: params.to_unsafe_h,
          headers: request_headers

        render json: use_case.process
      else
        render json: {status: "disabled"}
      end
    end

    def toggle
      @step.update_attributes(preview_enabled: !@step.preview_enabled)
      redirect_to @step
    end

    # POST /steps
    def create
      @step = @step_class.new(step_params)

      if @step.save
        redirect_to @step, notice: "Step was successfully created."
      else
        render :new
      end
    end

    # PATCH/PUT /steps/1
    def update
      if @step.update(step_params)
        redirect_to @step, notice: "Step was successfully updated."
      else
        render :edit
      end
    end

    # DELETE /steps/1
    def destroy
      @step.destroy
      redirect_to steps_url, notice: "Step was successfully destroyed."
    end

    private

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure,
        timeout: 0.5
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    def set_step_class
      class_name = params.fetch(:step, {}).delete(:type) ||
        params.delete(:type)
      class_name = RiddlerAdmin::Step.default_class.name if class_name.blank?

      @step_class = class_name.constantize
    end

    # Only allow a trusted parameter "white list" through.
    def step_params
      params.require(:step).permit(:title, :name, :type, :stepable_type, :stepable_id, :include_predicate)
    end
  end
end

app/helpers/riddler_admin/steps_helper.rb
module RiddlerAdmin
  module StepsHelper
  end
end

app/views/riddler_admin/steps/content/_show.html.erb
<div class="row" style="margin-bottom: 32px;">
  <div class="col-sm">

    <ul id="step-tabs" class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" id="elements-tab" data-toggle="tab" href="#elements" role="tab" aria-controls="elements" aria-selected="true">Elements</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="step-actions-tab" data-toggle="tab" href="#step-actions" role="tab" aria-controls="step-actions" aria-selected="false">Actions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="step-definition-tab" data-toggle="tab" href="#step-definition" role="tab" aria-controls="step-definition" aria-selected="false">Definition</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="step-preview-tab" data-toggle="tab" href="#step-preview" role="tab" aria-controls="step-preview" aria-selected="false">Preview</a>
      </li>
    </ul>

  </div>
</div>

<div class="row">
  <div class="col-sm">

    <div class="tab-content" id="step-tabs-content">
      <div class="tab-pane fade show active" id="elements" role="tabpanel" aria-labelledby="elements-tab">

        <div class="container">
          <div class="row">
            <div class="col-md-3">
              <h4>Add an element type</h4>

              <ul class="nav flex-column">
              <% RiddlerAdmin::Element.available_classes.each do |klass| %>
                <%= link_to "#{klass.short_name} Element", new_element_path(type: klass.name, step_id: @step.id), remote: true, class: 'nav-link' %>
              <% end %>
              </ul>

            </div>
            <div class="col-md-9">
              <div id="new-element">
              </div>

              <%= render partial: "riddler_admin/element_container", locals: { container: @step } %>

            </div>
          </div>
        </div>

      </div>

      <div class="tab-pane fade" id="step-actions" role="tabpanel" aria-labelledby="step-actions-tab">
        <%= render partial: "actions", locals: { step: @step } %>
      </div>

      <div class="tab-pane fade" id="step-definition" role="tabpanel" aria-labelledby="definition-tab">
        <%= render partial: "definition", object: @step %>
      </div>

      <div class="tab-pane fade" id="step-preview" role="tabpanel" aria-labelledby="preview-tab">
        <%= render partial: "riddler_admin/preview_step", locals: { preview_contexts: @preview_contexts, step: @step } %>
      </div>
    </div>

  </div>
</div>